### ISSUE TITLE
error on nmp start + no hosted demo

### ISSUE THREAD

**Issue by edouardbrasier** [nndung179/create-react-progressive-web-app#1]
Hi, 

I have tried to run your demo but I have the following errors.
Also it could be a good idea to add a hosted demo so we can see what your demo looks like.

Thanks

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! create-react-pwa-demo@0.1.0 start: `NODE_ENV='development' sw-precache --config=sw-precache-config.js && NODE_PATH='./src' react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-pwa-demo@0.1.0 start script 'NODE_ENV='development' sw-precache --config=sw-precache-config.js && NODE_PATH='./src' react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the create-react-pwa-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV='development' sw-precache --config=sw-precache-config.js && NODE_PATH='./src' react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs create-react-pwa-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls create-react-pwa-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Progressive\demoPWA\create-react-pwa-demo\npm-debug.log

**Comment by davidnguyen11** [comment]
which version of node are you using? You can follow this repo to set up project
[https://github.com/facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app)

I will update document with hosted demo later. Thank for the feedback!

**Comment by nndung179** [comment]
which version of node are you using? You can follow this repo to set up project

[https://github.com/facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app)

**Comment by edouardbrasier** [comment]
I have Node.js 6.9.1 (x64)
The hello world pwa react works.

cheers

**Comment by davidnguyen11** [comment]
Please provide version of npm or yarn

**Comment by edouardbrasier** [comment]
npm@3.10.8

**Comment by edouardbrasier** [comment]
I am going to reinstall node to see if it comes from my side.

**Comment by edouardbrasier** [comment]
So I have reinstalled everything but it still doesn't work.
For instance this works https://react.rocks/example/react-trello-board

**Comment by davidnguyen11** [comment]
hi @edouardbrasier,

I updated the `package.json`. Could you try again?. I also update the recorded video of this demo. So you can see how the demo looks like

**Comment by edouardbrasier** [comment]
Cool working now
