### ISSUE TITLE
Home Banner

### ISSUE THREAD

**Issue by edouardbrasier** [nndung179/create-react-progressive-web-app#2]
Does the home banner works for you?
I have tried to host jeffposnick/create-react-pwa demo with firebase but there is no home banner installation on my android.

**Comment by davidnguyen11** [comment]
I have just tested it. Look likes it only works in Chrome on Android.

**Comment by edouardbrasier** [comment]
Yes this is only supported by chrome.

What I meant is that it works with the original react pwa demo link
provided by Jeff as it adds a banner on my phone.
However when I recreated with "git clone" the code is working except the
banner. I get no error it just never installs the banner.

I am curious to see if you have the same issue.
Can you provide a url link of your demo?

I can tell you if it adds the banner or not.

Cheers

**Comment by edouardbrasier** [comment]
Well you might want to ignore thus issue because it looks like my own demo
is now working and installed a home banner on my phone.
I wonder why it didn't work the previous day. Perhaps the short name in the
manifest was too long.

**Comment by davidnguyen11** [comment]
@edouardbrasier I find something I think it is gonna be useful

[http://blog.teamtreehouse.com/optimizing-mobile-web-apps-ios](http://blog.teamtreehouse.com/optimizing-mobile-web-apps-ios)
