### ISSUE TITLE
Build is not Working on Apache server

### ISSUE THREAD

**Issue by jsk548** [nndung179/create-react-progressive-web-app#3]
Hi,
My build is not working on apache server. when i click  listitem on drawer it should go to product page "/product" but it is showing Object not Found.
Please help me in deploying this.

**Comment by jsk548** [comment]
any  update on this ?

**Comment by davidnguyen11** [comment]
Hi @jsk548 !!!

Sorry for late response. First I have no experience in deployment with Apache server. You can visit here to know more:

+ [https://stackoverflow.com/questions/42461279/how-to-deploy-a-react-app-on-apache-web-server](https://stackoverflow.com/questions/42461279/how-to-deploy-a-react-app-on-apache-web-server)

+ [https://stackoverflow.com/questions/42779037/deployment-of-react-js-application-to-apache-server-via-react-scripts](https://stackoverflow.com/questions/42779037/deployment-of-react-js-application-to-apache-server-via-react-scripts)

Or you can search on Google: "Deploy react appp with apache"
